---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sentryconnectors.itlabs.io
spec:
  scope: Cluster
  group: itlabs.io
  names:
    kind: SentryConnector
    plural: sentryconnectors
    singular: sentryconnector
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Sentry connector list defines instances of Sentry.
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values.'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase.'
              type: string
            metadata:
              type: object
            spec:
              type: object
              required: [
                "url",
                "token"
              ]
              properties:
                url:
                  description: Sentry URL
                  type: string
                organization:
                  description: The name of the Sentry organization to which the members belong
                  type: string
                  default: "sentry"
                token:
                  description: Path to Vault secret key containing access token
                  type: string
      additionalPrinterColumns:
        - name: URL
          type: string
          jsonPath: .spec.url
        - name: Organization
          type: string
          jsonPath: .spec.organization
