KEYCLOAK_INSTANCE_NAME_ANNOTATION = "keycloak.connector.itlabs.io/instance-name"
KEYCLOAK_VAULT_PATH_ANNOTATION = "keycloak.connector.itlabs.io/vault-path"
KEYCLOAK_CLIENT_ID_ANNOTATION = "keycloak.connector.itlabs.io/client-id"

KEYCLOAK_CONNECTOR_REQUIRED_ANNOTATIONS = (
    KEYCLOAK_INSTANCE_NAME_ANNOTATION,
    KEYCLOAK_VAULT_PATH_ANNOTATION,
    KEYCLOAK_CLIENT_ID_ANNOTATION,
)

KEYCLOAK_API_URL_KEY = "KEYCLOAK_API_URL"
KEYCLOAK_API_REALM_KEY = "KEYCLOAK_API_REALM"
KEYCLOAK_API_USERNAME_KEY = "KEYCLOAK_API_USERNAME"
KEYCLOAK_API_PASSWORD_KEY = "KEYCLOAK_API_PASSWORD"

KEYCLOAK_CLIENT_ID_KEY = "KEYCLOAK_CLIENT_ID"
KEYCLOAK_SECRET_KEY = "KEYCLOAK_SECRET_KEY"

KEYCLOAK_VAR_NAMES = (
    ("KEYCLOAK_CLIENT_ID", KEYCLOAK_CLIENT_ID_KEY),
    ("KEYCLOAK_SECRET_KEY", KEYCLOAK_SECRET_KEY),
)
