---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-itlabs-operator
  name: k8s-itlabs-operator
  namespace: k8s-itlabs-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-itlabs-operator
  template:
    metadata:
      labels:
        app: k8s-itlabs-operator
    spec:
      serviceAccountName: k8s-itlabs-operator
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: k8s-itlabs-operator
          image: $DOCKER_IMAGE
          imagePullPolicy: IfNotPresent
          command: [ '/bin/sh', '-c', 'poetry run kopf run --liveness=http://0.0.0.0:8090/healthz /app/main.py' ]
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
          ports:
            - name: awh
              containerPort: 443
            - name: metrics
              containerPort: 8080
            - name: healthz
              containerPort: 8090
          volumeMounts:
            - name: certs
              readOnly: true
              mountPath: /certs
          env:
            - name: AWH_PORT
              value: "443"
            - name: AWH_ADDR
              value: 0.0.0.0
            - name: AWH_HOST
              value: k8s-itlabs-operator.k8s-itlabs-operator.svc
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: VAULT_URL
              valueFrom:
                configMapKeyRef:
                  name: k8s-itlabs-operator-config
                  key: vault_url
            - name: VAULT_K8S_AUTH_METHOD
              valueFrom:
                configMapKeyRef:
                  name: k8s-itlabs-operator-config
                  key: vault_k8s_auth_method
            - name: VAULT_K8S_ROLE
              valueFrom:
                configMapKeyRef:
                  name: k8s-itlabs-operator-config
                  key: vault_k8s_role
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: k8s-itlabs-operator-config
                  key: cluster_name
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: itlabs-operator-sentry-dsn
                  key: sentry_dsn
                  optional: true
            - name: LOG_LEVEL
              value: DEBUG
      volumes:
        - name: certs
          secret:
            secretName: k8s-itlabs-operator
            optional: true
            items:
              - key: ca.crt
                path: ca
              - key: tls.crt
                path: cert
              - key: tls.key
                path: key
