---
apiVersion: v1
kind: Service
metadata:
  name: k8s-itlabs-operator
  namespace: k8s-itlabs-operator
  labels:
    app: k8s-itlabs-operator
spec:
  selector:
    app: k8s-itlabs-operator
  ports:
    - name: awh
      protocol: TCP
      port: 443
      targetPort: "awh"
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: "metrics"
    - name: healthz
      protocol: TCP
      port: 8090
      targetPort: "healthz"
