PG_CON_GROUP = 'itlabs.io'

PG_INSTANCE_NAME_ANNOTATION = 'postgres.connector.itlabs.io/instance-name'
VAULTPATH_NAME_ANNOTATION = 'postgres.connector.itlabs.io/vault-path'
DB_NAME_ANNOTATION = 'postgres.connector.itlabs.io/db-name'
USER_NAME_ANNOTATION = 'postgres.connector.itlabs.io/db-username'

PG_CON_REQUIRED_ANNOTATION_NAMES = (
    PG_INSTANCE_NAME_ANNOTATION,
    VAULTPATH_NAME_ANNOTATION,
)

APP_NAME_LABEL = 'app'

DATABASE_NAME_KEY = "DATABASE_NAME"
DATABASE_USER_KEY = "DATABASE_USER"
DATABASE_HOST_KEY = "DATABASE_HOST"
DATABASE_PORT_KEY = "DATABASE_PORT"
DATABASE_KUBE_DOMAIN_KEY = "DATABASE_KUBE_DOMAIN"
DATABASE_PASSWORD_KEY = "DATABASE_PASSWORD"

REQUIRED_POSTGRES_SECRET_KEYS = (
    DATABASE_HOST_KEY,
    DATABASE_PORT_KEY,
    DATABASE_NAME_KEY,
    DATABASE_USER_KEY,
    DATABASE_PASSWORD_KEY,
)

DATABASE_VAR_NAMES = (
    ('POSTGRES_DB_NAME', DATABASE_NAME_KEY),
    ('POSTGRES_DB_USER', DATABASE_USER_KEY),
    ('POSTGRES_DB_PASSWORD', DATABASE_PASSWORD_KEY),
    ('POSTGRES_DB_HOST', DATABASE_HOST_KEY),
    ('POSTGRES_DB_PORT', DATABASE_PORT_KEY),
)
