---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rabbitconnectors.itlabs.io
spec:
  scope: Cluster
  group: itlabs.io
  names:
    kind: RabbitConnector
    plural: rabbitconnectors
    singular: rabbitconnector
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Rabbit connector list defines instances of Rabbit.
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values.'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase.'
              type: string
            metadata:
              type: object
            spec:
              type: array
              items:
                description: Rabbit connector defines instance of Postgres.
                type: object
                properties:
                  name:
                    description: name of rabbit connector, should be unique for cluster.
                    type: string
                  vaultpath:
                    description: path to the secret in vault with credentials to rabbit instance for operator
                    type: string
