apiVersion: itlabs.io/v1
kind: PostgresConnector
metadata:
  name: postgres
spec:
  host: postgres.default
  port: 5432
  database: postgres
  username: vault:secret/data/infrastructure/postgres#USERNAME
  password: vault:secret/data/infrastructure/postgres#PASSWORD
  readonly-username: vault:secret/data/infrastructure/postgres#READONLY_USERNAME
