apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample
  name: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
      annotations:
        postgres.connector.itlabs.io/instance-name: postgres
        postgres.connector.itlabs.io/vault-path: vault:secret/data/application/postgres-credentials
        postgres.connector.itlabs.io/db-name: mydb
        postgres.connector.itlabs.io/db-username: myuser
    spec:
      containers:
      - image: alpine:3.15
        name: alpine
