---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgresconnectors.itlabs.io
spec:
  scope: Cluster
  group: itlabs.io
  names:
    kind: PostgresConnector
    plural: postgresconnectors
    singular: postgresconnector
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Postgres connector list defines instances of Postgres.
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values.'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase.'
              type: string
            metadata:
              type: object
            spec:
              type: object
              required: [
                "host",
                "username",
                "password"
              ]
              properties:
                host:
                  description: Postgres host name
                  type: string
                port:
                  description: Postgres port number
                  type: integer
                  default: 5432
                database:
                  description: Postgres database name
                  type: string
                  default: "postgres"
                username:
                  description: Path to Vault secret key containing username for connection to the databsae
                  type: string
                password:
                  description: Path to Vault secret key containing password for connection to the database
                  type: string
                readonly-username:
                  description: Path to Vault secret key containing username for readonly access to the database
                  type: string
      additionalPrinterColumns:
        - name: Host
          type: string
          jsonPath: .spec.host
        - name: Port
          type: integer
          jsonPath: .spec.port
