---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakconnectors.itlabs.io
spec:
  scope: Cluster
  group: itlabs.io
  names:
    kind: KeycloakConnector
    plural: keycloakconnectors
    singular: keycloakconnector
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Keycloak connector list defines instances of Keycloak.
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values.'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase.'
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                url:
                  description: Keycloak location (include host and port)
                  type: string
                realm:
                  description: Realm name
                  type: string
                username:
                  description: Path to Vault secret key containing username
                  type: string
                password:
                  description: Path to Vault secret key containing password
                  type: string
      additionalPrinterColumns:
        - name: URL
          type: string
          jsonPath: .spec.url
        - name: Realm
          type: string
          jsonPath: .spec.realm
