---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: keycloak-connector
  annotations:
    cert-manager.io/inject-ca-from: k8s-itlabs-operator/k8s-itlabs-operator
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      namespace: k8s-itlabs-operator
      name: k8s-itlabs-operator
      path: /kk-con-on-createpods
      port: 443
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: create-pods.keycloak-connector.itlabs.io
  namespaceSelector:
    matchExpressions:
      - key: name
        operator: NotIn
        values:
          - k8s-itlabs-operator
          - kube-system
          - vswh
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - kube-system
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ''
    apiVersions:
    - v1
    operations:
    - '*'
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
