name: gitlab-sync

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ closed ]

jobs:
  trigger-pipeline:
    name: Trigger Gitlab pipeline
    runs-on: ubuntu-latest
    needs: [ lint, unit-tests, e2e-tests ]
    if: github.event.pull_request.merged == true
    steps:
      - name: Run pipeline
        env:
          URL: ${{ secrets.GITLAB_URL }}
          TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          curl -X POST --fail -F token=${TOKEN} -F ref=github ${URL}
